# Generated by Django 3.0.4 on 2020-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_num', models.IntegerField()),
                ('a1', models.IntegerField()),
                ('a2', models.IntegerField()),
                ('a3', models.IntegerField()),
                ('a4', models.IntegerField()),
                ('a5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_num', models.IntegerField()),
                ('q1', models.CharField(max_length=300)),
                ('q2', models.CharField(max_length=300)),
                ('q3', models.CharField(max_length=300)),
                ('q4', models.CharField(max_length=300)),
                ('a1', models.IntegerField()),
                ('a2', models.IntegerField()),
                ('a3', models.IntegerField()),
                ('a4', models.IntegerField()),
                ('a5', models.IntegerField()),
            ],
        ),
    ]
